include: _default_template_yaml
dataset_path: <add absolute ref>/CausalVQA/experiments/Causal_VQA_test_set/Anticipation_easy/
dataset_kwargs:
  load_from_disk: true

task: anticipation_easy
dataset_name: Anticipation_easy
test_split: valid
metric_list:
  - metric: paired_accuracy 
    aggregation: !function utils.easy_ant_pair_accuracy
    higher_is_better: true
  - metric: single_accuracy 
    aggregation: !function utils.easy_ant_sing_accuracy
    higher_is_better: true
