include: _default_template_yaml
dataset_path: <add absolute ref>/CausalVQA/experiments/Causal_VQA_test_set/Counterfactual_easy/
dataset_kwargs:
  load_from_disk: true

task: counterfactual_easy
dataset_name: Counterfactual_easy
test_split: valid
metric_list:
  - metric: paired_accuracy 
    aggregation: !function utils.easy_cou_pair_accuracy
    higher_is_better: true
  - metric: single_accuracy 
    aggregation: !function utils.easy_cou_sing_accuracy
    higher_is_better: true
