include: _default_template_yaml
dataset_path: <add absolute ref>/CausalVQA/experiments/Causal_VQA_test_set/Hypothetical_med/
dataset_kwargs:
  load_from_disk: true

task: hypothetical_med
dataset_name: Hypothetical_med
test_split: valid
metric_list:
  - metric: paired_accuracy 
    aggregation: !function utils.med_hyp_pair_accuracy
    higher_is_better: true
  - metric: single_accuracy 
    aggregation: !function utils.med_hyp_sing_accuracy
    higher_is_better: true
