include: _default_template_yaml
dataset_path: <add absolute ref>/CausalVQA/experiments/Causal_VQA_test_set/Planning_easy/
dataset_kwargs:
  load_from_disk: true

task: planning_easy
dataset_name: Planning_easy
test_split: valid
metric_list:
  - metric: paired_accuracy 
    aggregation: !function utils.easy_pla_pair_accuracy
    higher_is_better: true
  - metric: single_accuracy 
    aggregation: !function utils.easy_pla_sing_accuracy
    higher_is_better: true
