include: _default_template_yaml
dataset_path: <add absolute ref>/CausalVQA/experiments/Causal_VQA_test_set/Planning_med/
dataset_kwargs:
  load_from_disk: true

task: planning_med
dataset_name: Planning_med
test_split: valid
metric_list:
  - metric: paired_accuracy 
    aggregation: !function utils.med_pla_pair_accuracy
    higher_is_better: true
  - metric: single_accuracy 
    aggregation: !function utils.med_pla_sing_accuracy
    higher_is_better: true
